name: Dart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1.3

      - name: Install dependencies
        run: |
          cd dart_sdk
          dart pub get
          
      - name: Verify formatting
        run: |
          cd dart_sdk
          dart format --output=none --set-exit-if-changed .

      - name: Analyze project source
        run: |
          cd dart_sdk
          dart analyze

      - name: Run tests
        run: |
          cd dart_sdk
          dart test
